config/routes.rb
Rails.application.routes.draw do
  root to: 'application#main'
  resources :users
  get '/home' => 'users#home', as: 'user_home'
  resources :schedules
  resources :events, defaults: { format: 'json'}
  resources :venues, defaults: { format: 'json' }
  get '/top_venues' => 'venues#top_venues', as: 'top_venues'

  # ---Sessions---
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/error' => 'sessions#error'
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :schedules
	belongs_to :venue
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_many :users
	has_and_belongs_to_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :schedule
	has_many :events

	has_secure_password
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	belongs_to :event

	# def get_top_venues
		# create method to get sort top venues
	# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def main
    @venues = Venue.all.sort_by { |venue| venue.popularity_rating }
    @venues.reverse!
  end

  def current_user
  	User.find_by(id: session[:current_user]) if session[:current_user]
  end

  def authenticate?
  	redirect_to error_path unless current_user
  end

  def authorize
  	unless current_user && current_user.id == params[:id].to_i
  		redirect_to error_path
  	end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authorize, only: [:edit]


	def index
		if current_user
			@events = Event.all
			@events = Event.where(creator_id: current_user.id)
		else
			@events = Event.all
			respond_to do |format|
				format.json { render :json => @events }
			end
		end
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		params[:creator_id] = current_user.id
		params[:creator] = current_user.username
		@event = Event.new(:creator_id => params[:creator_id], :creator => params[:creator])
	end

	def create
		params[:creator_id] = current_user.id
		params[:creator] = current_user.username
		@event = Event.new(event_params)
		if @event.save
			redirect_to user_home_path
		else
			render :new
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@event.update(event_params)
		redirect_to events_path
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	private
	def event_params
		params.require(:event).permit(:name, :creator, :street_address, :number_in_attendance, :price, :venue_name, :duration, :event_type, :calendar_date, :host_name, :number_males_attending, :number_females_attending, :city, :state, :zip_code, :creator_id, :public_view, :private_view)
	end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_action :authorize, only: [:edit]

	def index
		if current_user
			@schedules = Schedule.all
			@schedules = Schedule.where(creator_id: current_user.id)
		else
			@schedules = Schedule.all
		end
	end

	def show
		@schedule = Schedule.find(params[:id])
	end

	def new
		params[:creator_id] = current_user.id
		params[:creator] = current_user.username
		@schedule = Schedule.new(:creator_id => params[:creator_id], :creator => params[:creator])
	end

	def create
		params[:creator_id] = current_user.id
		params[:creator] = current_user.username
		@schedule = Schedule.new(schedule_params)
		if @schedule.save
			redirect_to user_home_path
		else
			render :new
		end
	end

	def edit
		@schedule = Schedule.find(params[:id])
	end

	def update
		@schedule = Schedule.find(params[:id])
		@schedule.update(schedule_params)
		redirect_to schedule_path(@schedule.id)
	end

	def destroy
		@schedule = Schedule.find(params[:id])
		@schedule.destroy
		redirect_to schedules_path
	end

	private
	def schedule_params
		params.require(:schedule).permit(:name, :creator, :public_view, :private_view, :creator_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:current_user] = user.id
			redirect_to user_home_path
		else
			flash.now[:login_error] = "That's not your email (or password)."
			render :new
		end
	end

	def destroy
		session[:current_user] = nil
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authorize, only: [:edit, :update, :destroy]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to root_path
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end

	def home
		@user = current_user
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :gender, :age, :zip_code, :street_address, :city, :state, :interest, :username, :email, :profile_type, :telephone_number, :password, :password_confirmation, :image)
	end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	def index
		@venues = Venue.all
		respond_to do |format|
			format.json { render :json => @venues }
		end
	end

	def top_venues
		@venues = Venue.all.sort_by { |venue| venue.popularity_rating }
		@venues.reverse!
		render json: @venues[0..4]
	end

	private
	# params.require(:venue).permit(:name, :street, :city, :state, :country, :latitude, :longitude, :popularity_rating)
	def venue_params
		params.require(:venue).permit(:name, :street, :city, :state, :country, :latitude, :longitude, :popularity_rating)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/main.html.erb
<!-- CHANGE TO BOOTSTRAP GRID -->
		<div id="HotSpot">
			<div class="form-inline">
				<div class="form-group">
					<form id="SearchBox" action="#">
						<input id="SearchInput" type="text" name="Search" placeholder="Search Venue or Events"/>
						<a href="#"><%= image_tag 'Search.png', id:'SearchIcon' %></a>
					</form>
				</div>
			</div>
			<div id="HeaderEvent"><span class="Text icon icon-crown">TOP 5 HOT SPOTS</span></div>

			<div id="HeaderTimeLine">
				<div id="HeaderDate">
					<button id="Arrow" class="icon icon-backwards"></button>
					<input id="InputDate" class="Text" value=""/>
					<button id="Arrow" class="icon icon-forwards"></button>
					<input id="InputTime" class="Text" />
				</div>

				<div id="TimeWindow">
					<div id="Time">
						<span id="Hour1" class="TimeAxis"></span><span id="Hour2" class="TimeAxis"></span><span id="Hour3" class="TimeAxis"></span><span id="Hour4" class="TimeAxis"></span><span id="Hour5" class="TimeAxis"></span><span id="Hour6" class="TimeAxis"></span><span id="Hour7" class="TimeAxis"></span>
					</div><!--Time-->
				</div><!--TimeWindow-->
			</div><!--HeaderTimeLine-->

			<div id="HeaderOptions"><span class="Text">LOGO</span></div>

			<div id="Title">
				<ol>
					<%	@venues[0..4].each do |venue| %>
						<li>Venue Name: <%= venue.name %><br>
						Popularity Rating: <%= venue.popularity_rating %></li>
						<br>
					<% end %>
				</ol>
			</div><!--Title-->



			<div id="Timeline">
				<div class="TimeArrow icon icon-back faded"></div>
				<div class="TimeArrow icon icon-next faded"></div>
			</div><!--Timeline-->

			<div id="Options">
				<form id="SearchOption" action="#">
					<div id=filterName><h4>Categories</h4></div>
					<input type="checkbox" name="option" value="option1"/>Option1 <br />
					<input type="checkbox" name="option" value="option2"/>Option2 <br />
					<input type="checkbox" name="option" value="option3"/>Option3 <br />
					<input type="checkbox" name="option" value="option4"/>Option4 <br />
					<input type="checkbox" name="option" value="option5"/>Option5 <br />
					<input type="checkbox" name="option" value="option6"/>Option6 <br />
					<input type="submit" value="Filter" id="SearchButton"/>
				</form>
			</div><!--Options-->

			<div id="FooterEvent"><span class="Text"><%= link_to 'View All Venues', venues_path %></span></div>
			<div id="FooterSlider"><span class="Text"> | | | | | </span></div>
			<div id="FooterOptions"></div>

		</div> <!--HotSpot-->

app/views/events/_form.html.erb
<div class="form-horizontal">
	<%= form_for @event do |f| %>
		<div class="form-group">
			<%= f.label :name, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :name, class: "form-control", placeholder: "Enter a name for the event" %>
			</div>
		</div>
		<div>
			<%= f.text_field :creator_id, style: "#{'display:none'}" %>
			<%= f.text_field :creator, style: "#{'display:none'}" %>
		</div>
		<div class="form-group">
			<%= f.label :number_in_attendance, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :number_in_attendance, class: "form-control", placeholder: "Enter the number of people going" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :number_males_attending, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :number_males_attending, class: "form-control", placeholder: "Enter number of males attending" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :number_females_attending, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :number_females_attending, class: "form-control", placeholder: "Enter number of females going" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :price, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :price, class: "form-control", placeholder: "Enter price of event" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :venue_name, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :venue_name, class: "form-control", placeholder: "Enter venue name" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :duration, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :duration, class: "form-control", placeholder: "Enter duration of event" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :calendar_date, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :calendar_date, class: "form-control", placeholder: "Enter date of event" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :street_address, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :street_address, class: "form-control", placeholder: "Enter the street address" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :city, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :city, class: "form-control", placeholder: "Enter the city" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :state, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :state, class: "form-control", placeholder: "Enter the state" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :zip_code, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :zip_code, class: "form-control", placeholder: "Enter the zip code" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :host_name, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :host_name, class: "form-control", placeholder: "Enter the host's name" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :event_type, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :event_type, class: "form-control", placeholder: "Enter the event type" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :make_private, nil, class: "col-sm-2 control-label", :hidden => true %>
			<div class="col-sm-offset-2 col-sm-10">
				<div class="checkbox">
					<label>
						<%= f.check_box :private_view, :checked => :false %>Make Private
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<%= f.submit 'Submit', class: "btn btn-primary btn-large btn-block" %>
			</div>
		</div>
	<% end %>
</div>

app/views/events/edit.html.erb
<h3>Edit Event Information</h3>

<%= render 'form' %>

<%= link_to 'Delete Event', event_path(@event), method: :delete %><br><br>
<%= link_to '<< Back to Event Page', event_path(@event.id) %>

app/views/events/index.html.erb
<h3>Events Index Page</h3>
<hr>
<% @events.each do |event| %>
	Event ID: <%= event.id %><br>
	Name of Event: <%= link_to "#{event.name}", event_path(event.id) %><br>
	Event Creator: <%= event.creator %><br>
	Number Going To Event: <%= event.number_in_attendance %><br>
	Males Going: <%= event.number_males_attending %><br>
	Females Going: <%= event.number_females_attending %><br>
	Price: <%= event.price %><br>
	Venue: <%= event.venue_name %><br>
	Duration: <%= event.duration %><br>
	When: <%= event.calendar_date %><br>
	Where: <%= event.street_address %><br>
				<%= event.city %>, <%= event.state %> <%= event.zip_code %><br>
	Host: <%= event.host_name %><br>
	Type of Event: <%= event.event_type %><br>
	Created at: <%= event.created_at %><br>
	<hr>
<% end %>

app/views/events/new.html.erb
<div class="container-fluid">

	<h2>Create Event</h2>

	<%= render 'form' %>

	<%= link_to 'Back to Events Index', events_path %>
</div>

app/views/events/show.html.erb
<h3>Event Page for <%= @event.name %></h3>

Name of Event: <%= @event.name %><br>
Event Creator: <%= @event.creator %><br>
Number Going To Event: <%= @event.number_in_attendance %><br>
Males Going: <%= @event.number_males_attending %><br>
Females Going: <%= @event.number_females_attending %><br>
Price: <%= @event.price %><br>
Venue: <%= @event.venue_name %><br>
Duration: <%= @event.duration %><br>
When: <%= @event.calendar_date %><br>
Where: <%= @event.street_address %><br>
			<%= @event.city %>, <%= @event.state %> <%= @event.zip_code %><br>
Host: <%= @event.host_name %><br>
Type of Event: <%= @event.event_type %><br>
Created at: <%= @event.created_at %><br>

<%= link_to 'Edit Event', edit_event_path %><br><br>
<%= link_to '<< Back Events Index Page', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoundThere</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="nav">
			<h1>Navigation Header</h1>
			<%= link_to 'Home', root_path %> |
			<% if current_user %>
				<%= link_to 'Create Event', new_event_path %> |
				<%= link_to 'Create Schedule', new_schedule_path %> |
				<%= link_to 'Schedules Index', schedules_path %> |
				<%= link_to 'Events Index', events_path %><br><br>
			<% else %>
				<%= link_to 'Sign Up', new_user_path %> |
				<%= link_to 'Log In', login_path %>
			<% end %>
		</div>
		<% if current_user %>
			<div id="user-info">
				Welcome back, <span><strong><%= current_user.username %></strong></span>! |
				<%= link_to 'Edit Profile', edit_user_path(current_user) %> |
				<%= link_to 'Logout', logout_path %>
			</div>
		<% end %>
	</header>
	<hr>
	<div id="content">
		<%= yield %>
	</div>

</body>
</html>

app/views/schedules/_form.html.erb
<div class="form-horizontal">
	<%= form_for @schedule do |f| %>
		<div class="form-group">
			<%= f.label :name, class: "col-sm-2 control-label" %>
			<div class="col-sm-2">
				<%= f.text_field :name, class: "form-control", placeholder: "Enter the name" %>
			</div>
		</div>
		<div><%= f.text_field :creator_id, style: "#{'display:none'}" %>
			<%= f.text_field :creator, style: "#{'display:none'}" %>
		</div>
		<div class="form-group">
			<%= f.label :view_type, class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
				<div class="radio-inline">
					<%= f.radio_button :public_view, 'public view', :checked => false %>
					<%= f.label :public_view %>
				</div>
				<div class="radio-inline">
					<%= f.radio_button :private_view, 'private view', :checked => false %>
					<%= f.label :private_view %>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-2">
				<%= f.submit 'Submit', class: "btn btn-primary btn-large btn-block" %>
			</div>
		</div>
	<% end %>
</div>

app/views/schedules/edit.html.erb
<h3>Edit Schedule</h3>

<%= render 'form' %>

<%= link_to 'Delete Schedule', schedule_path(@schedule), method: :delete %><br><br>
<%= link_to '<< Back to Schedule Page', schedule_path(@schedule.id) %>

app/views/schedules/index.html.erb
<h3>Schedule Index Page</h3>
<hr>
<% @schedules.each do |schedule| %>
	Name: <%= link_to "#{schedule.name}", schedule_path(schedule.id) %><br>
	Schedule Creator: <%= schedule.creator %><br>
	Public View: <%= schedule.public_view %><br>
	Private View: <%= schedule.private_view %><br>
	<hr>
<% end %>

app/views/schedules/new.html.erb
<div class="container-fluid">
	<h2>Create Schedule</h2>

	<%= render 'form' %>

	<%= link_to '<< Back to Users Index Page', users_path %>
</div>

app/views/schedules/show.html.erb
<h3>Schedule Page</h3>

Schedule ID: <%= @schedule.id %><br>
Name: <%= @schedule.name %><br>
Schedule Creator: <%= @schedule.creator %><br>
Public View: <%= @schedule.public_view %><br>
Private View: <%= @schedule.private_view %><br>

<%= link_to 'Edit Schedule', edit_schedule_path %><br>
<%= link_to '<< Back to Schedules Index Page', schedules_path %>

app/views/users/_form.html.erb
<div class="form-horizontal">
	<%= form_for @user do |f| %>
		<div class="form-group" >
			<%= f.label :first_name, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :first_name, class: "form-control", placeholder: "Enter your first name" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :last_name, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :last_name, class: "form-control", placeholder: "Enter your last name" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :email, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.text_field :email, class: "form-control", placeholder: "Enter your email" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :password, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
			<div class="col-sm-4">
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :gender, class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
				<div class="radio-inline">
					<%= f.radio_button :gender, 'male', :checked => false %>
					<%= f.label :gender, 'Male' %>
				</div>
				<div class="radio-inline">
					<%= f.radio_button :gender, 'female', :checked => false %>
					<%= f.label :gender, 'Female' %>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<%= f.submit 'Sign Up', class: "btn btn-primary btn-large btn-block" %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit <%= "#{@user.first_name}" %>'s Profile</h2>
<%= render 'form' %>
<%= link_to 'Delete Profile', user_path(@user), method: :delete %>
<br>
<br>
<%= link_to 'Back to Homepage', root_path %>

app/views/users/home.html.erb
<h1><%= @user.first_name.capitalize %>'s HomePage</h1>

app/views/users/index.html.erb
<h2>Users Index Page</h2>
<ul>
	<hr>
	<% @users.each do |user| %>
		User ID: <%= link_to "#{user.id}", user_path(user.id) %><br>
		First Name: <%= user.first_name %><br>
		Last Name: <%= user.last_name %><br>
		Gender: <%= user.gender %>
		<hr>
	<% end %>
</ul>

app/views/users/new.html.erb
<div class="container-fluid">
	<h2>Sign Up</h2>
	<%= render 'form' %>

	<%= link_to 'Back to Users Index', users_path %>
</div>

app/views/users/show.html.erb
<h2><%= @user.first_name.capitalize %>'s Profile Page</h2>
User ID: <%= @user.id %><br>
First Name: <%= @user.first_name %><br>
Last Name: <%= @user.last_name %><br>
Gender: <%= @user.gender %><br>

<%= link_to 'Edit Profile', edit_user_path %>

app/views/venues/index.html.erb
<h1>Venues Index</h1>

<hr>
<ul>
	<%	@venues.each do |venue| %>
		<li>Venue Name: <%= venue.name %></li>
		Popularity Rating: <%= venue.popularity_rating %>
	<hr>
	<% end %>
</ul>

app/views/venues/top_venues.html.erb
<h1>Top Venues</h1>